/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.aaa.data.model.impl;

import com.liferay.aaa.data.model.Dservice;
import com.liferay.aaa.data.model.DserviceModel;
import com.liferay.aaa.data.model.DserviceSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Dservice service. Represents a row in the &quot;DM_Dservice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.aaa.data.model.DserviceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DserviceImpl}.
 * </p>
 *
 * @author Rishikesh Dubey
 * @see DserviceImpl
 * @see com.liferay.aaa.data.model.Dservice
 * @see com.liferay.aaa.data.model.DserviceModel
 * @generated
 */
@JSON(strict = true)
public class DserviceModelImpl extends BaseModelImpl<Dservice>
	implements DserviceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dservice model instance should use the {@link com.liferay.aaa.data.model.Dservice} interface instead.
	 */
	public static final String TABLE_NAME = "DM_Dservice";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "dserviceId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "serviceTitle", Types.VARCHAR },
			{ "serviceDescription", Types.VARCHAR },
			{ "serviceRate", Types.VARCHAR },
			{ "serviceDuration", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DM_Dservice (uuid_ VARCHAR(75) null,dserviceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,serviceTitle VARCHAR(75) null,serviceDescription VARCHAR(75) null,serviceRate VARCHAR(75) null,serviceDuration VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DM_Dservice";
	public static final String ORDER_BY_JPQL = " ORDER BY dservice.dserviceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DM_Dservice.dserviceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.aaa.data.model.Dservice"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.aaa.data.model.Dservice"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.aaa.data.model.Dservice"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static long DSERVICEID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Dservice toModel(DserviceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Dservice model = new DserviceImpl();

		model.setUuid(soapModel.getUuid());
		model.setDserviceId(soapModel.getDserviceId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setServiceTitle(soapModel.getServiceTitle());
		model.setServiceDescription(soapModel.getServiceDescription());
		model.setServiceRate(soapModel.getServiceRate());
		model.setServiceDuration(soapModel.getServiceDuration());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Dservice> toModels(DserviceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Dservice> models = new ArrayList<Dservice>(soapModels.length);

		for (DserviceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.aaa.data.model.Dservice"));

	public DserviceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dserviceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDserviceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dserviceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Dservice.class;
	}

	@Override
	public String getModelClassName() {
		return Dservice.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("dserviceId", getDserviceId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("serviceTitle", getServiceTitle());
		attributes.put("serviceDescription", getServiceDescription());
		attributes.put("serviceRate", getServiceRate());
		attributes.put("serviceDuration", getServiceDuration());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long dserviceId = (Long)attributes.get("dserviceId");

		if (dserviceId != null) {
			setDserviceId(dserviceId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String serviceTitle = (String)attributes.get("serviceTitle");

		if (serviceTitle != null) {
			setServiceTitle(serviceTitle);
		}

		String serviceDescription = (String)attributes.get("serviceDescription");

		if (serviceDescription != null) {
			setServiceDescription(serviceDescription);
		}

		String serviceRate = (String)attributes.get("serviceRate");

		if (serviceRate != null) {
			setServiceRate(serviceRate);
		}

		String serviceDuration = (String)attributes.get("serviceDuration");

		if (serviceDuration != null) {
			setServiceDuration(serviceDuration);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDserviceId() {
		return _dserviceId;
	}

	@Override
	public void setDserviceId(long dserviceId) {
		_dserviceId = dserviceId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getServiceTitle() {
		if (_serviceTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceTitle;
		}
	}

	@Override
	public void setServiceTitle(String serviceTitle) {
		_serviceTitle = serviceTitle;
	}

	@JSON
	@Override
	public String getServiceDescription() {
		if (_serviceDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceDescription;
		}
	}

	@Override
	public void setServiceDescription(String serviceDescription) {
		_serviceDescription = serviceDescription;
	}

	@JSON
	@Override
	public String getServiceRate() {
		if (_serviceRate == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceRate;
		}
	}

	@Override
	public void setServiceRate(String serviceRate) {
		_serviceRate = serviceRate;
	}

	@JSON
	@Override
	public String getServiceDuration() {
		if (_serviceDuration == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceDuration;
		}
	}

	@Override
	public void setServiceDuration(String serviceDuration) {
		_serviceDuration = serviceDuration;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Dservice.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Dservice.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Dservice toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Dservice)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DserviceImpl dserviceImpl = new DserviceImpl();

		dserviceImpl.setUuid(getUuid());
		dserviceImpl.setDserviceId(getDserviceId());
		dserviceImpl.setGroupId(getGroupId());
		dserviceImpl.setCompanyId(getCompanyId());
		dserviceImpl.setUserId(getUserId());
		dserviceImpl.setUserName(getUserName());
		dserviceImpl.setCreateDate(getCreateDate());
		dserviceImpl.setModifiedDate(getModifiedDate());
		dserviceImpl.setServiceTitle(getServiceTitle());
		dserviceImpl.setServiceDescription(getServiceDescription());
		dserviceImpl.setServiceRate(getServiceRate());
		dserviceImpl.setServiceDuration(getServiceDuration());

		dserviceImpl.resetOriginalValues();

		return dserviceImpl;
	}

	@Override
	public int compareTo(Dservice dservice) {
		long primaryKey = dservice.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Dservice)) {
			return false;
		}

		Dservice dservice = (Dservice)obj;

		long primaryKey = dservice.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DserviceModelImpl dserviceModelImpl = this;

		dserviceModelImpl._originalUuid = dserviceModelImpl._uuid;

		dserviceModelImpl._originalGroupId = dserviceModelImpl._groupId;

		dserviceModelImpl._setOriginalGroupId = false;

		dserviceModelImpl._originalCompanyId = dserviceModelImpl._companyId;

		dserviceModelImpl._setOriginalCompanyId = false;

		dserviceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Dservice> toCacheModel() {
		DserviceCacheModel dserviceCacheModel = new DserviceCacheModel();

		dserviceCacheModel.uuid = getUuid();

		String uuid = dserviceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dserviceCacheModel.uuid = null;
		}

		dserviceCacheModel.dserviceId = getDserviceId();

		dserviceCacheModel.groupId = getGroupId();

		dserviceCacheModel.companyId = getCompanyId();

		dserviceCacheModel.userId = getUserId();

		dserviceCacheModel.userName = getUserName();

		String userName = dserviceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dserviceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dserviceCacheModel.createDate = createDate.getTime();
		}
		else {
			dserviceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dserviceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dserviceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dserviceCacheModel.serviceTitle = getServiceTitle();

		String serviceTitle = dserviceCacheModel.serviceTitle;

		if ((serviceTitle != null) && (serviceTitle.length() == 0)) {
			dserviceCacheModel.serviceTitle = null;
		}

		dserviceCacheModel.serviceDescription = getServiceDescription();

		String serviceDescription = dserviceCacheModel.serviceDescription;

		if ((serviceDescription != null) && (serviceDescription.length() == 0)) {
			dserviceCacheModel.serviceDescription = null;
		}

		dserviceCacheModel.serviceRate = getServiceRate();

		String serviceRate = dserviceCacheModel.serviceRate;

		if ((serviceRate != null) && (serviceRate.length() == 0)) {
			dserviceCacheModel.serviceRate = null;
		}

		dserviceCacheModel.serviceDuration = getServiceDuration();

		String serviceDuration = dserviceCacheModel.serviceDuration;

		if ((serviceDuration != null) && (serviceDuration.length() == 0)) {
			dserviceCacheModel.serviceDuration = null;
		}

		return dserviceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", dserviceId=");
		sb.append(getDserviceId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", serviceTitle=");
		sb.append(getServiceTitle());
		sb.append(", serviceDescription=");
		sb.append(getServiceDescription());
		sb.append(", serviceRate=");
		sb.append(getServiceRate());
		sb.append(", serviceDuration=");
		sb.append(getServiceDuration());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.aaa.data.model.Dservice");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dserviceId</column-name><column-value><![CDATA[");
		sb.append(getDserviceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceTitle</column-name><column-value><![CDATA[");
		sb.append(getServiceTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceDescription</column-name><column-value><![CDATA[");
		sb.append(getServiceDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceRate</column-name><column-value><![CDATA[");
		sb.append(getServiceRate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceDuration</column-name><column-value><![CDATA[");
		sb.append(getServiceDuration());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Dservice.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Dservice.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _dserviceId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _serviceTitle;
	private String _serviceDescription;
	private String _serviceRate;
	private String _serviceDuration;
	private long _columnBitmask;
	private Dservice _escapedModel;
}